import type { Request, Response } from "express";
import https from "https";
import http from "http";
import fs from "fs";
import path from "path";
import os from "os";
import crypto from "crypto";
import { Op } from "sequelize";
import { ok, created, noContent } from "../../utils/response.js";
import { HttpError } from "../../middlewares/errorHandler.js";
import { logger } from "../../lib/logger.js";
import { BackgroundTrack, BackgroundTrackSettings, Content } from "../../models/index.js";
import { storageProvider } from "../../storage/index.js";
import { backgroundTrackMixService } from "../../services/BackgroundTrackMixService.js";
import { env } from "../../config/env.js";

const MAX_UPLOAD_BYTES = 10 * 1024 * 1024; // 10 MB
const DOWNLOAD_TIMEOUT_MS = 20_000;
const ALLOWED_EXTS = new Set(["mp3", "wav", "ogg"]);

/* ─── Tracks CRUD ────────────────────────────────────────────────────────── */

export async function listTracks(req: Request, res: Response): Promise<void> {
  const { category, source, limit = "50", offset = "0" } = req.query as Record<string, string>;

  const where: Record<string, unknown> = {};
  if (category) where["category"] = category;
  if (source) where["source"] = source;

  const { rows, count } = await BackgroundTrack.findAndCountAll({
    where,
    limit: Math.min(Number(limit), 200),
    offset: Number(offset),
    order: [["createdAt", "DESC"]],
  });

  ok(res, { items: rows, total: count, limit: Number(limit), offset: Number(offset) });
}

export async function getTrack(req: Request, res: Response): Promise<void> {
  const id = req.params["id"] as string;
  const track = await BackgroundTrack.findByPk(id);
  if (!track) throw new HttpError("Trilha não encontrada", 404);
  ok(res, track);
}

export async function createTrack(req: Request, res: Response): Promise<void> {
  const body = req.body as {
    name: string;
    url: string;
    category?: string;
    duration_seconds?: number;
    tags?: string[];
  };

  if (!body.name || !body.url) throw new HttpError("name e url são obrigatórios", 400);

  // Validate URL
  try { new URL(body.url); } catch {
    throw new HttpError("url deve ser uma URL válida", 400);
  }

  const track = await BackgroundTrack.create({
    name: body.name,
    url: body.url,
    category: body.category ?? "generico",
    duration_seconds: body.duration_seconds ?? null,
    tags: body.tags ?? [],
    source: "manual",
  });

  logger.info("admin: background track created", { id: track.id, name: track.name });
  created(res, track, "Trilha criada");
}

export async function updateTrack(req: Request, res: Response): Promise<void> {
  const track = await BackgroundTrack.findByPk(req.params["id"] as string);
  if (!track) throw new HttpError("Trilha não encontrada", 404);

  const body = req.body as Partial<{
    name: string;
    url: string;
    category: string;
    duration_seconds: number;
    tags: string[];
  }>;

  await track.update({
    ...(body.name && { name: body.name }),
    ...(body.url && { url: body.url }),
    ...(body.category && { category: body.category }),
    ...(body.duration_seconds !== undefined && { duration_seconds: body.duration_seconds }),
    ...(body.tags && { tags: body.tags }),
  });

  // If URL changed, invalidate cache
  if (body.url) {
    await backgroundTrackMixService.invalidateCacheForTrack(track.id);
  }

  logger.info("admin: background track updated", { id: track.id });
  ok(res, track, "Trilha atualizada");
}

export async function deleteTrack(req: Request, res: Response): Promise<void> {
  const track = await BackgroundTrack.findByPk(req.params["id"] as string);
  if (!track) throw new HttpError("Trilha não encontrada", 404);

  // Invalidate all mixes using this track
  await backgroundTrackMixService.invalidateCacheForTrack(track.id);

  // Remove from storage if it was generated by us
  if (track.source === "elevenlabs") {
    try {
      const key = track.url.split("/").pop();
      if (key) await storageProvider.delete(`background-tracks/${key}`);
    } catch { /* non-fatal */ }
  }

  await track.destroy();
  logger.info("admin: background track deleted", { id: track.id });
  noContent(res);
}

/* ─── Generate via ElevenLabs Music ─────────────────────────────────────── */

export async function generateTrack(req: Request, res: Response): Promise<void> {
  const body = req.body as {
    prompt: string;
    duration_seconds?: number;
    category?: string;
    name?: string;
  };

  if (!body.prompt) throw new HttpError("prompt é obrigatório", 400);

  const apiKey = env.elevenLabsApiKey;
  if (!apiKey) throw new HttpError("ELEVENLABS_API_KEY não configurado", 503);

  const duration = Math.min(Math.max(body.duration_seconds ?? 60, 10), 300);
  logger.info("admin: generating background track via ElevenLabs", { prompt: body.prompt.slice(0, 80), duration });

  // Call ElevenLabs Music API
  const audioBuffer = await callElevenLabsMusic(apiKey, body.prompt, duration);

  // Save to temp then upload
  const hash = crypto.randomBytes(8).toString("hex");
  const tmpPath = path.join(os.tmpdir(), `bg-el-${hash}.mp3`);
  fs.writeFileSync(tmpPath, audioBuffer);

  let url: string;
  try {
    const key = `background-tracks/el-${Date.now()}-${hash}.mp3`;
    url = await storageProvider.upload(tmpPath, key);
  } finally {
    try { fs.unlinkSync(tmpPath); } catch { /* ignore */ }
  }

  const track = await BackgroundTrack.create({
    name: body.name ?? `IA – ${body.prompt.slice(0, 60)}`,
    url,
    category: (body.category as BackgroundTrack["category"]) ?? "generico",
    duration_seconds: duration,
    tags: ["ia", "elevenlabs"],
    source: "elevenlabs",
    prompt: body.prompt,
  });

  logger.info("admin: ElevenLabs background track created", { id: track.id, url });
  created(res, track, "Trilha gerada e salva");
}

async function callElevenLabsMusic(apiKey: string, prompt: string, durationSeconds: number): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const payload = JSON.stringify({ prompt, duration_seconds: durationSeconds });
    const timer = setTimeout(() => reject(new Error("ElevenLabs Music timeout (30s)")), 30_000);

    const options = {
      hostname: "api.elevenlabs.io",
      path: "/v1/music",
      method: "POST",
      headers: {
        "xi-api-key": apiKey,
        "Content-Type": "application/json",
        "Content-Length": Buffer.byteLength(payload),
        "Accept": "audio/mpeg",
      },
    };

    const req = https.request(options, (res) => {
      if (res.statusCode && (res.statusCode < 200 || res.statusCode >= 300)) {
        clearTimeout(timer);
        reject(new HttpError(`ElevenLabs Music API retornou HTTP ${res.statusCode}`, 502));
        return;
      }

      const chunks: Buffer[] = [];
      res.on("data", (chunk: Buffer) => chunks.push(chunk));
      res.on("end", () => { clearTimeout(timer); resolve(Buffer.concat(chunks)); });
      res.on("error", (e) => { clearTimeout(timer); reject(e); });
    });

    req.on("error", (e) => { clearTimeout(timer); reject(e); });
    req.write(payload);
    req.end();
  });
}

/* ─── Settings ───────────────────────────────────────────────────────────── */

export async function listSettings(_req: Request, res: Response): Promise<void> {
  const rows = await BackgroundTrackSettings.findAll({ order: [["content_type", "ASC"]] });
  ok(res, rows);
}

export async function getSettings(req: Request, res: Response): Promise<void> {
  const { contentType } = req.params as { contentType: string };
  const settings = await BackgroundTrackSettings.findByPk(contentType);
  if (!settings) throw new HttpError(`Configuração para "${contentType}" não encontrada`, 404);
  ok(res, settings);
}

export async function upsertSettings(req: Request, res: Response): Promise<void> {
  const { contentType } = req.params as { contentType: string };

  const VALID_TYPES = ["oracao", "reflexao", "mensagem"];
  if (!VALID_TYPES.includes(contentType)) {
    throw new HttpError(`Tipo inválido. Válidos: ${VALID_TYPES.join(", ")}`, 400);
  }

  const body = req.body as Partial<{
    enabled: boolean;
    volume_base: number;
    ducking_db: number;
    fade_in_ms: number;
    fade_out_ms: number;
    default_category: string;
  }>;

  const [settings, created_] = await BackgroundTrackSettings.upsert({
    content_type: contentType,
    ...(body.enabled !== undefined && { enabled: body.enabled }),
    ...(body.volume_base !== undefined && { volume_base: body.volume_base }),
    ...(body.ducking_db !== undefined && { ducking_db: body.ducking_db }),
    ...(body.fade_in_ms !== undefined && { fade_in_ms: body.fade_in_ms }),
    ...(body.fade_out_ms !== undefined && { fade_out_ms: body.fade_out_ms }),
    ...(body.default_category !== undefined && { default_category: body.default_category }),
  });

  // Settings changed → invalidate all cached mixes of this type
  await backgroundTrackMixService.invalidateCacheForType(contentType);

  logger.info("admin: background track settings updated", { contentType });
  ok(res, settings, created_ ? "Configuração criada" : "Configuração atualizada");
}

/* ─── On-demand remix ────────────────────────────────────────────────────── */

export async function remixContent(req: Request, res: Response): Promise<void> {
  const contentId = Number(req.params["contentId"]);
  if (!Number.isFinite(contentId) || contentId <= 0) throw new HttpError("contentId inválido", 400);

  const content = await Content.findByPk(contentId);
  if (!content) throw new HttpError("Conteúdo não encontrado", 404);
  if (!content.audio_url) throw new HttpError("Conteúdo não tem audio_url — faça a síntese TTS primeiro", 422);

  const contentData = content as unknown as {
    id: number; tipo: string; audio_url: string;
    mixed_audio_url: string | null; background_track_id: string | null;
  };

  // Force re-mix by clearing cached URL first
  await Content.update({ mixed_audio_url: null }, { where: { id: contentId } });
  contentData.mixed_audio_url = null;

  const t0 = Date.now();
  const mixedUrl = await backgroundTrackMixService.mix(contentData);

  if (!mixedUrl) {
    throw new HttpError(
      "Nenhuma trilha disponível para este tipo de conteúdo ou mixagem desabilitada", 422,
    );
  }

  logger.info("admin: content remixed on demand", { contentId, mixedUrl, ms: Date.now() - t0 });
  ok(res, { contentId, mixedUrl, ms: Date.now() - t0 }, "Mix concluído");
}
