import { Model, DataTypes, type Sequelize } from "sequelize";

export type BackgroundTrackCategory = "oracao" | "reflexao" | "mensagem" | "generico";
export type BackgroundTrackSource = "manual" | "elevenlabs";

export class BackgroundTrack extends Model {
  declare id: string;          // UUID
  declare name: string;
  declare url: string;
  declare category: BackgroundTrackCategory;
  declare duration_seconds: number | null;
  declare tags: string[];
  declare source: BackgroundTrackSource;
  declare prompt: string | null;
  declare createdAt: Date;
}

export function initBackgroundTrack(sequelize: Sequelize): void {
  BackgroundTrack.init(
    {
      id: {
        type: DataTypes.UUID,
        defaultValue: DataTypes.UUIDV4,
        primaryKey: true,
      },
      name: { type: DataTypes.STRING(255), allowNull: false },
      url: { type: DataTypes.TEXT, allowNull: false, comment: "Public URL of the MP3/WAV/OGG file in storage" },
      category: {
        type: DataTypes.ENUM("oracao", "reflexao", "mensagem", "generico"),
        allowNull: false,
        defaultValue: "generico",
      },
      duration_seconds: { type: DataTypes.DECIMAL(10, 2), allowNull: true },
      tags: { type: DataTypes.ARRAY(DataTypes.STRING), allowNull: false, defaultValue: [] },
      source: {
        type: DataTypes.ENUM("manual", "elevenlabs"),
        allowNull: false,
        defaultValue: "manual",
      },
      prompt: { type: DataTypes.TEXT, allowNull: true, comment: "Prompt used if generated by ElevenLabs" },
    },
    {
      sequelize,
      modelName: "BackgroundTrack",
      tableName: "background_tracks",
      timestamps: true,
      updatedAt: false,
      indexes: [
        { fields: ["category"] },
        { fields: ["source"] },
      ],
    },
  );
}
